name : Dev Deployment from github and build docker image and push to azure container registry
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker login to Azure Container Registry
      - name: Docker login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: WhiteshopAcr.azurecr.io
          username: ${{secrets.AZURE_USERNAME}}
          password: ${{secrets.AZURE_PASSWORD}}
      # Build Docker image
      - name: Build Docker image
        run: 
          docker build -t WhiteshopAcr.azurecr.io/ai-preprocess:${{github.sha}} .
      # Push Docker image to Azure Container Registry
      - name: Push Docker image to Azure Container Registry
        run:
          docker push WhiteshopAcr.azurecr.io/ai-preprocess:${{github.sha}}
