name : Dev Deployment from github and build docker image and push to azure container registry
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker login to Azure Container Registry
      - name: Docker login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: WhiteshopAcr.azurecr.io
          username: ${{secrets.AZURE_USERNAME}}
          password: ${{secrets.AZURE_PASSWORD}}
      # Build Docker image
      - name: Build Docker image
        run: 
          docker build -t WhiteshopAcr.azurecr.io/ai-preprocess:${{github.sha}} .
      # Push Docker image to Azure Container Registry
      - name: Push Docker image to Azure Container Registry
        run:
          docker push WhiteshopAcr.azurecr.io/ai-preprocess:${{github.sha}}

  # Deploy to Azure Web App
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Azure login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{secrets.AZURE_CREDENTIALS}}

  #     - name: Azure webapp deploy
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{secrets.AZURE_WEBAPP}}
  #         images: WhiteshopAcr.azurecr.io/ai-preprocess:${{github.sha}}
  #         slot-name: production

#deploy to kubernetes cluster
  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Checkout k8s repo
        uses: actions/checkout@v2
        with:
          repository: mohiuddin1221/k8s
          ref: "main"
          token: ${{ secrets.G_TOKEN }}

      - name: Setup Git config
        run: |
          git config --global user.email "topumohiuddin3@gmail.com"
          git config --global user.name "mohiuddin1221"

      - name: Update image tag in ai-preprocess.yaml
        run: |
          sed -i "s#\(WhiteshopAcr.azurecr.io/ai-preprocess:\)[^\"']*#\1${{ github.sha }}#g" ai-preprocess.yaml

      - name: Commit and push changes
        run: |
          git add ai-preprocess.yaml
          git commit -m "Update ai-preprocess image to WhiteshopAcr.azurecr.io/ai-preprocess:${{ github.sha }}" || echo "No changes"
          git pull origin main --rebase
          git push origin main
